server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/shuixinmeng/lemeng_20171108/
          searchPaths:
          username:
          password:
      label: master